import PrintableForm from "./PrintableForm";
import { formatFullAadhaar } from "../../utils/aadhaar";

/**
 * The only component that renders a complete Aadhaar number for printing.
 *
 * Everything it shows is passed in: the record comes from application state and
 * the number plus the provenance line come from the print-payload response the
 * server issued against a verified print authorization. It reads nothing back out
 * of the page, so a value edited through developer tools in the visible details
 * form does not reach the printer.
 *
 * Mounted only for the duration of one print and unmounted immediately after, so
 * the full number is not sitting in the document between exports.
 *
 * This raises the integrity of browser printing; it does not make it
 * tamper-proof. The markup still lives in a page the user controls, and someone
 * determined to alter it before the print dialog opens can. The server-generated
 * PDF is the path that removes that possibility — see the confidential-PDF
 * endpoint.
 */
export default function ConfidentialAppointmentPrint({
  record,
  payload,
  formRef,
}) {
  if (!record || !payload) return null;

  const data = {
    ...record,
    // Grouped in fours, as printed on the card itself.
    aadharNo: formatFullAadhaar(payload.aadhaarFull),
    containsFullAadhaar: true,
    printedBy: payload.generatedBy,
  };

  return (
    // The ref goes on the wrapper, not on the form inside it: the print window is
    // handed this node's outerHTML, and anchoring it to the form alone would leave
    // the provenance block below out of the printed sheet.
    <div ref={formRef} data-confidential-print-root>
      <PrintableForm data={data} />

      {/* Provenance travels with the paper. A sheet found on a desk names who
          produced it, when, and under which audited authorization. */}
      <div className="mt-3 border-2 border-black px-3 py-2 text-black">
        <p className="text-[11px] font-black uppercase tracking-widest">
          Confidential — Contains Sensitive Identity Information
        </p>
        <p className="mt-1 text-[10px] font-medium leading-relaxed">
          Generated by: {payload.generatedBy || "—"}
          <br />
          Generated at: {payload.generatedAt || "—"}
          <br />
          Export reference: {payload.exportReference || "—"}
          <br />
          Record: {payload.recordLabel || record.appointmentNumber || "—"}
        </p>
        <p className="mt-1 text-[9px] font-medium">
          This printed copy is outside application access control. Handle
          according to company privacy policy.
        </p>
      </div>
    </div>
  );
}
