
function formatDate(value) {
  if (!value || value === "-") return "";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value === "-" ? "" : value;
  return date.toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
}

const PrintableForm = ({ data, formRef }) => {
  const nameParts = (data.fullName || "").split(" ").filter(Boolean);
  let firstName = "";
  let midName = "";
  let surname = "";
  
  if (nameParts.length === 1) {
    firstName = nameParts[0];
  } else if (nameParts.length === 2) {
    firstName = nameParts[0];
    surname = nameParts[1];
  } else if (nameParts.length >= 3) {
    firstName = nameParts[0];
    midName = nameParts.slice(1, -1).join(" ");
    surname = nameParts[nameParts.length - 1];
  }

  return (
    <div
      ref={formRef}
      data-appointment-print-form
      className="bg-white p-6 text-black border border-dotted border-gray-600 mx-auto w-full min-w-[720px] max-w-[850px] shadow-sm font-sans"
    >
      {/* Marks any copy — on screen, printed or exported — that carries a
          complete Aadhaar number, so a sheet found on a desk is identifiable as
          sensitive. Driven by the caller's view model, never inferred here. */}
      {data.containsFullAadhaar && (
        <div className="mb-2 border-2 border-black px-2 py-1 text-center">
          <p className="text-[11px] font-black uppercase tracking-widest">
            Confidential — Contains Sensitive Identity Information
          </p>
          <p className="text-[9px] font-medium">
            {data.printedBy ? `Generated by ${data.printedBy} · ` : ""}
            {data.appointmentNumber || ""}
          </p>
        </div>
      )}

      <div className="text-center mb-0">
        <h1 className="inline-block text-xl font-black tracking-widest uppercase">
          APPOINTMENT FORM
        </h1>
      </div>
      <div className="border-t-2 border-black mt-2 mb-6"></div>

      {/* Grid of Photo and Personal Details */}
      <div className="grid grid-cols-12 gap-8 items-start">
        <div className="col-span-5 flex flex-col items-center">
          <div className="w-48 h-56 border border-gray-400 flex items-center justify-center bg-gray-50 overflow-hidden">
            {data.photo ? (
              <img
                src={data.photo}
                alt="Profile"
                className="w-full h-full object-cover"
              />
            ) : (
              <div className="text-center">
                <p className="font-bold text-gray-400">NO PHOTO</p>
              </div>
            )}
          </div>
        </div>

        <div className="col-span-7 space-y-3 w-full">
          <div className="w-full">
            <div className="flex flex-row items-end gap-2 py-1 w-full">
              <label className="text-[13px] font-bold text-black whitespace-nowrap w-[130px] shrink-0 leading-normal">
                Emp. Code
              </label>
              <span className="font-bold text-black inline">:</span>
              <span className="flex-grow border-b border-black px-1 min-h-[20px] pb-0.5 text-[13px] uppercase font-medium leading-none">
                {data.empCode || ""}
              </span>
            </div>
          </div>

          <div className="w-full">
            <div className="flex flex-row items-end gap-2 py-1 w-full">
              <label className="text-[13px] font-bold text-black whitespace-nowrap w-[130px] shrink-0 leading-normal">
                Joining Date
              </label>
              <span className="font-bold text-black inline">:</span>
              <span className="flex-grow border-b border-black px-1 min-h-[20px] pb-0.5 text-[13px] font-medium leading-none">
                {formatDate(data.joiningDate)}
              </span>
            </div>
          </div>

          <div className="w-full">
            <div className="flex flex-row items-end gap-2 py-1 w-full">
              <label className="text-[13px] font-bold text-black whitespace-nowrap w-[130px] shrink-0 leading-normal">
                Department
              </label>
              <span className="font-bold text-black inline">:</span>
              <span className="flex-grow border-b border-black px-1 min-h-[20px] pb-0.5 text-[13px] uppercase font-medium leading-none">
                {data.department || ""}
              </span>
            </div>
          </div>

          <div className="w-full">
            <div className="flex flex-row items-end gap-2 py-1 w-full">
              <label className="text-[13px] font-bold text-black whitespace-nowrap w-[130px] shrink-0 leading-normal">
                Designation
              </label>
              <span className="font-bold text-black inline">:</span>
              <span className="flex-grow border-b border-black px-1 min-h-[20px] pb-0.5 text-[13px] uppercase font-medium leading-none">
                {data.designation || ""}
              </span>
            </div>
          </div>

          <div className="w-full">
            <div className="flex flex-row items-end gap-2 py-1 w-full">
              <label className="text-[13px] font-bold text-black whitespace-nowrap w-[130px] shrink-0 leading-normal">
                Manager Name
              </label>
              <span className="font-bold text-black inline">:</span>
              <span className="flex-grow border-b border-black px-1 min-h-[20px] pb-0.5 text-[13px] uppercase font-medium leading-none">
                {data.managerName || ""}
              </span>
            </div>
          </div>

          <div className="w-full">
            <div className="flex flex-row items-end gap-2 py-1 w-full">
              <label className="text-[13px] font-bold text-black whitespace-nowrap w-[130px] shrink-0 leading-normal">
                Salary
              </label>
              <span className="font-bold text-black inline">:</span>
              <span className="flex-grow border-b border-black px-1 min-h-[20px] pb-0.5 text-[13px] font-medium leading-none">
                {data.salary || ""}
              </span>
            </div>
          </div>

          <div className="w-full">
            <div className="flex flex-row items-end gap-2 py-1 w-full">
              <label className="text-[13px] font-bold text-black whitespace-nowrap w-[130px] shrink-0 leading-normal">
                Emp. Mobile No
              </label>
              <span className="font-bold text-black inline">:</span>
              <span className="flex-grow border-b border-black px-1 min-h-[20px] pb-0.5 text-[13px] font-medium leading-none">
                {data.empMobile || ""}
              </span>
            </div>
          </div>

          <div className="w-full">
            <div className="flex flex-row items-end gap-2 py-1 w-full">
              <label className="text-[13px] font-bold text-black whitespace-nowrap w-[130px] shrink-0 leading-normal">
                Emp. Whatsapp No
              </label>
              <span className="font-bold text-black inline">:</span>
              <span className="flex-grow border-b border-black px-1 min-h-[20px] pb-0.5 text-[13px] font-medium leading-none">
                {data.empWhatsapp || ""}
              </span>
            </div>
          </div>
        </div>
      </div>

      <div className="mt-6 space-y-4">
        <div className="flex flex-row items-end gap-2 py-1">
          <label className="font-bold w-[130px] shrink-0 text-[13px] text-black">
            Punching No
          </label>
          <span className="font-bold text-black inline">:</span>
          <span className="border-b border-black w-48 px-1 min-h-[20px] pb-0.5 text-[13px] font-medium leading-none">
            {data.punchingNo || ""}
          </span>
        </div>

        <div className="flex flex-row items-end gap-2 py-1">
          <label className="font-bold w-[130px] shrink-0 text-[13px] text-black">
            Name
          </label>
          <span className="font-bold text-black inline">:</span>
          <div className="flex-grow grid grid-cols-3 gap-4">
            <div className="text-center flex flex-col">
              <span className="w-full border-b border-black px-1 min-h-[20px] pb-0.5 text-[13px] uppercase font-bold leading-none text-center">
                {firstName || ""}
              </span>
              <span className="text-[10px] text-gray-700 font-bold block mt-1">
                (FIRST NAME)
              </span>
            </div>
            <div className="text-center flex flex-col">
              <span className="w-full border-b border-black px-1 min-h-[20px] pb-0.5 text-[13px] uppercase font-bold leading-none text-center">
                {midName || ""}
              </span>
              <span className="text-[10px] text-gray-700 font-bold block mt-1">
                (MID NAME)
              </span>
            </div>
            <div className="text-center flex flex-col">
              <span className="w-full border-b border-black px-1 min-h-[20px] pb-0.5 text-[13px] uppercase font-bold leading-none text-center">
                {surname || ""}
              </span>
              <span className="text-[10px] text-gray-700 font-bold block mt-1">
                (SURNAME)
              </span>
            </div>
          </div>
        </div>

        <div className="w-full">
          <div className="flex flex-row items-end gap-2 py-1 w-full">
            <label className="text-[13px] font-bold text-black whitespace-nowrap w-[130px] shrink-0 leading-normal">
              Email
            </label>
            <span className="font-bold text-black inline">:</span>
            <span className="flex-grow border-b border-black px-1 min-h-[20px] pb-0.5 text-[13px] font-medium leading-none">
              {data.email || ""}
            </span>
          </div>
        </div>

        <div className="w-full">
          <div className="flex flex-row items-end gap-2 py-1 w-full">
            <label className="text-[13px] font-bold text-black whitespace-nowrap w-[130px] shrink-0 leading-normal">
              Resident Add
            </label>
            <span className="font-bold text-black inline">:</span>
            <span className="flex-grow border-b border-black px-1 min-h-[20px] pb-0.5 text-[13px] font-medium leading-none">
              {data.address || ""}
            </span>
          </div>
        </div>

        <div className="grid grid-cols-3 gap-6 w-full">
          <div className="min-w-0">
            <div className="flex flex-row items-end gap-2 py-1">
              <label className="text-[13px] font-bold text-black whitespace-nowrap shrink-0 leading-normal">
                Village
              </label>
              <span className="font-bold text-black inline">:</span>
              <span className="w-full border-b border-black px-1 min-h-[20px] pb-0.5 text-[13px] uppercase font-medium leading-none">
                {data.village || ""}
              </span>
            </div>
          </div>

          <div className="min-w-0">
            <div className="flex flex-row items-end gap-2 py-1">
              <label className="text-[13px] font-bold text-black whitespace-nowrap shrink-0 leading-normal">
                Taluka
              </label>
              <span className="font-bold text-black inline">:</span>
              <span className="w-full border-b border-black px-1 min-h-[20px] pb-0.5 text-[13px] uppercase font-medium leading-none">
                {data.taluka || ""}
              </span>
            </div>
          </div>

          <div className="min-w-0">
            <div className="flex flex-row items-end gap-2 py-1">
              <label className="text-[13px] font-bold text-black whitespace-nowrap shrink-0 leading-normal">
                District
              </label>
              <span className="font-bold text-black inline">:</span>
              <span className="w-full border-b border-black px-1 min-h-[20px] pb-0.5 text-[13px] uppercase font-medium leading-none">
                {data.district || ""}
              </span>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-2 gap-x-12 gap-y-3">
          <div className="w-full">
            <div className="flex flex-row items-end gap-2 py-1 w-full">
              <label className="text-[13px] font-bold text-black whitespace-nowrap w-[130px] shrink-0 leading-normal">
                Birth Date
              </label>
              <span className="font-bold text-black inline">:</span>
              <span className="flex-grow border-b border-black px-1 min-h-[20px] pb-0.5 text-[13px] font-medium leading-none">
                {formatDate(data.dob)}
              </span>
            </div>
          </div>

          <div className="w-full">
            <div className="flex flex-row items-end gap-2 py-1 w-full">
              <label className="text-[13px] font-bold text-black whitespace-nowrap w-[130px] shrink-0 leading-normal">
                Birth Place
              </label>
              <span className="font-bold text-black inline">:</span>
              <span className="flex-grow border-b border-black px-1 min-h-[20px] pb-0.5 text-[13px] uppercase font-medium leading-none">
                {data.birthPlace || ""}
              </span>
            </div>
          </div>

          <div className="w-full">
            <div className="flex flex-row items-end gap-2 py-1 w-full">
              <label className="text-[13px] font-bold text-black whitespace-nowrap w-[130px] shrink-0 leading-normal">
                Gender
              </label>
              <span className="font-bold text-black inline">:</span>
              <span className="flex-grow border-b border-black px-1 min-h-[20px] pb-0.5 text-[13px] uppercase font-medium leading-none">
                {data.gender || ""}
              </span>
            </div>
          </div>

          <div className="w-full">
            <div className="flex flex-row items-end gap-2 py-1 w-full">
              <label className="text-[13px] font-bold text-black whitespace-nowrap w-[130px] shrink-0 leading-normal">
                Cast
              </label>
              <span className="font-bold text-black inline">:</span>
              <span className="flex-grow border-b border-black px-1 min-h-[20px] pb-0.5 text-[13px] uppercase font-medium leading-none">
                {data.cast || ""}
              </span>
            </div>
          </div>

          <div className="w-full">
            <div className="flex flex-row items-end gap-2 py-1 w-full">
              <label className="text-[13px] font-bold text-black whitespace-nowrap w-[130px] shrink-0 leading-normal">
                Marital Status
              </label>
              <span className="font-bold text-black inline">:</span>
              <span className="flex-grow border-b border-black px-1 min-h-[20px] pb-0.5 text-[13px] uppercase font-medium leading-none">
                {data.maritalStatus || ""}
              </span>
            </div>
          </div>

          <div className="w-full">
            <div className="flex flex-row items-end gap-2 py-1 w-full">
              <label className="text-[13px] font-bold text-black whitespace-nowrap w-[130px] shrink-0 leading-normal">
                Blood Group
              </label>
              <span className="font-bold text-black inline">:</span>
              <span className="flex-grow border-b border-black px-1 min-h-[20px] pb-0.5 text-[13px] uppercase font-medium leading-none">
                {data.bloodGroup || ""}
              </span>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-2 gap-x-12 gap-y-3">
          <div className="w-full">
            <div className="flex flex-row items-end gap-2 py-1 w-full">
              <label className="text-[13px] font-bold text-black whitespace-nowrap w-[130px] shrink-0 leading-normal">
                Reference Name
              </label>
              <span className="font-bold text-black inline">:</span>
              <span className="flex-grow border-b border-black px-1 min-h-[20px] pb-0.5 text-[13px] uppercase font-medium leading-none">
                {data.refName || ""}
              </span>
            </div>
          </div>

          <div className="w-full">
            <div className="flex flex-row items-end gap-2 py-1 w-full">
              <label className="text-[13px] font-bold text-black whitespace-nowrap w-[130px] shrink-0 leading-normal">
                Reference Mobile
              </label>
              <span className="font-bold text-black inline">:</span>
              <span className="flex-grow border-b border-black px-1 min-h-[20px] pb-0.5 text-[13px] font-medium leading-none">
                {data.refMobile || ""}
              </span>
            </div>
          </div>

          <div className="w-full">
            <div className="flex flex-row items-end gap-2 py-1 w-full">
              <label className="text-[13px] font-bold text-black whitespace-nowrap w-[130px] shrink-0 leading-normal">
                Aadhaar Card No
              </label>
              <span className="font-bold text-black inline">:</span>
              <span className="flex-grow border-b border-black px-1 min-h-[20px] pb-0.5 text-[13px] font-medium leading-none">
                {/* Already resolved by the caller's view model — masked or full
                    depending on what the server returned for this viewer. This
                    component never decides. */}
                {data.aadharNo || ""}
              </span>
            </div>
          </div>

          <div className="w-full">
            <div className="flex flex-row items-end gap-2 py-1 w-full">
              <label className="text-[13px] font-bold text-black whitespace-nowrap w-[130px] shrink-0 leading-normal">
                Bank Name
              </label>
              <span className="font-bold text-black inline">:</span>
              <span className="flex-grow border-b border-black px-1 min-h-[20px] pb-0.5 text-[13px] uppercase font-medium leading-none">
                {data.bankName || ""}
              </span>
            </div>
          </div>

          <div className="w-full">
            <div className="flex flex-row items-end gap-2 py-1 w-full">
              <label className="text-[13px] font-bold text-black whitespace-nowrap w-[130px] shrink-0 leading-normal">
                PAN Card No
              </label>
              <span className="font-bold text-black inline">:</span>
              <span className="flex-grow border-b border-black px-1 min-h-[20px] pb-0.5 text-[13px] uppercase font-medium leading-none">
                {data.panNo || ""}
              </span>
            </div>
          </div>

          <div className="w-full">
            <div className="flex flex-row items-end gap-2 py-1 w-full">
              <label className="text-[13px] font-bold text-black whitespace-nowrap w-[130px] shrink-0 leading-normal">
                Bank IFSC Code
              </label>
              <span className="font-bold text-black inline">:</span>
              <span className="flex-grow border-b border-black px-1 min-h-[20px] pb-0.5 text-[13px] uppercase font-medium leading-none">
                {data.ifscCode || ""}
              </span>
            </div>
          </div>

          <div className="w-full">
            <div className="flex flex-row items-end gap-2 py-1 w-full">
              <label className="text-[13px] font-bold text-black whitespace-nowrap w-[130px] shrink-0 leading-normal">
                Education
              </label>
              <span className="font-bold text-black inline">:</span>
              <span className="flex-grow border-b border-black px-1 min-h-[20px] pb-0.5 text-[13px] uppercase font-medium leading-none">
                {data.education || ""}
              </span>
            </div>
          </div>

          <div className="w-full">
            <div className="flex flex-row items-end gap-2 py-1 w-full">
              <label className="text-[13px] font-bold text-black whitespace-nowrap w-[130px] shrink-0 leading-normal">
                Bank Account No
              </label>
              <span className="font-bold text-black inline">:</span>
              <span className="flex-grow border-b border-black px-1 min-h-[20px] pb-0.5 text-[13px] font-medium leading-none">
                {data.accountNo || ""}
              </span>
            </div>
          </div>
        </div>
      </div>

      <div className="mt-6 overflow-visible pb-4">
        <table className="w-full border-collapse border border-black text-[13px] min-w-[600px]">
          <thead>
            <tr className="font-bold bg-gray-50">
              <th className="border border-black p-1 w-12 text-center">Sr No</th>
              <th className="border border-black p-1">Family Members Name</th>
              <th className="border border-black p-1">Relation</th>
              <th className="border border-black p-1">D.O.B.</th>
              <th className="border border-black p-1">Mobile No</th>
              <th className="border border-black p-1">Occupation</th>
            </tr>
          </thead>
          <tbody>
            {Array.from({ length: 4 }).map((_, index) => {
              const member = data.members?.[index] || {};
              return (
                <tr key={index} className="h-8">
                  <td className="border border-black text-center font-bold">{index + 1}</td>
                  <td className="border border-black px-2 py-1 font-medium">{member.name || ""}</td>
                  <td className="border border-black px-2 py-1 text-center uppercase font-medium">{member.relation || ""}</td>
                  <td className="border border-black px-2 py-1 text-center font-medium">{formatDate(member.dob)}</td>
                  <td className="border border-black px-2 py-1 text-center font-medium">{member.mobile || ""}</td>
                  <td className="border border-black px-2 py-1 text-center uppercase font-medium">{member.occupation || ""}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      <div className="mt-10 grid grid-cols-3 gap-6 font-bold text-[13px]">
        <div>
          <p className="mb-1">Check By, Manager</p>
          <div className="border-b border-black w-full h-8"></div>
        </div>
        <div className="text-center">
          <p className="mb-1">Confirm By,</p>
          <div className="border-b border-black w-full h-8"></div>
          <p className="mt-1 font-normal">(Ketanbhai)</p>
        </div>
        <div className="text-center">
          <p className="mb-1">Auth. By,</p>
          <div className="border-b border-black w-full h-8"></div>
          <p className="mt-1 font-normal">HR Dept</p>
        </div>
      </div>

      <div className="mt-6 flex flex-row justify-between items-end gap-10">
        <div className="flex flex-col gap-2 flex-1 w-full">
          <div className="flex flex-row items-center gap-2 w-full">
            <span className="font-bold whitespace-nowrap uppercase text-[12px] text-black">Company :</span>
            <span className="border-b border-black flex-grow px-1 min-h-[20px] pb-0.5 text-[13px] uppercase font-bold leading-none">
              {data.companyId || data.companyCode || data.company_code || data.companyName || data.company || ""}
            </span>
          </div>
          <div className="flex flex-row items-center gap-2 w-full">
            <span className="font-bold whitespace-nowrap uppercase text-[12px] text-black">UNIT NAME :</span>
            <span className="border-b border-black flex-grow px-1 min-h-[20px] pb-0.5 text-[13px] uppercase font-bold leading-none">
              {data.unitName || ""}
            </span>
          </div>
        </div>
        <div className="flex flex-row items-center gap-2 flex-1 w-full">
          <span className="font-bold whitespace-nowrap uppercase text-[12px] text-black">Emp. Signature :</span>
          <span className="border-b border-black flex-grow px-1 min-h-[20px] pb-0.5 text-[13px] uppercase font-bold leading-none">
            {data.signature || ""}
          </span>
        </div>
      </div>
    </div>
  );
};

export default PrintableForm;
