import { describe, it, expect } from "vitest";
import { render, screen } from "@testing-library/react";

import PrintableForm from "./PrintableForm";

/**
 * This form renders whatever Aadhaar value its caller resolved — it never
 * decides masked vs full itself. Appointment Details builds one view model and
 * hands it to both the on-screen copy and the hidden copy that Print and PDF
 * serialise, so the three cannot disagree.
 */

const masked = {
  fullName: "Parth R Patel",
  appointmentNumber: "APT-000104",
  aadharNo: "XXXX XXXX 8793",
  panNo: "ABCDE1234E",
};

const full = {
  ...masked,
  aadharNo: "7151 1598 8793",
  containsFullAadhaar: true,
  printedBy: "Nisha HR",
};

describe("PrintableForm — Aadhaar rendering", () => {
  it("uses the correct spelling for the label", () => {
    render(<PrintableForm data={masked} />);

    expect(screen.getByText("Aadhaar Card No")).toBeInTheDocument();
    expect(screen.queryByText("Aadhar Card No")).toBeNull();
  });

  it("renders the masked value it was given", () => {
    const { container } = render(<PrintableForm data={masked} />);

    expect(screen.getByText("XXXX XXXX 8793")).toBeInTheDocument();
    expect(container.textContent).not.toContain("7151 1598 8793");
  });

  it("renders the full value it was given", () => {
    render(<PrintableForm data={full} />);

    expect(screen.getByText("7151 1598 8793")).toBeInTheDocument();
  });

  it("offers no Show or Hide control", () => {
    render(<PrintableForm data={full} />);

    expect(screen.queryByRole("button", { name: /^show$/i })).toBeNull();
    expect(screen.queryByRole("button", { name: /^hide$/i })).toBeNull();
  });

  it("marks a copy carrying the full number as confidential", () => {
    render(<PrintableForm data={full} />);

    expect(
      screen.getByText(/Confidential — Contains Sensitive Identity Information/i),
    ).toBeInTheDocument();
    expect(screen.getByText(/Generated by Nisha HR/)).toBeInTheDocument();
    expect(screen.getByText(/APT-000104/)).toBeInTheDocument();
  });

  it("adds no confidential marking to a masked copy", () => {
    render(<PrintableForm data={masked} />);

    expect(screen.queryByText(/Confidential/i)).toBeNull();
  });

  it("never puts the Aadhaar in the confidential header itself", () => {
    render(<PrintableForm data={full} />);

    const banner = screen
      .getByText(/Confidential — Contains Sensitive Identity Information/i)
      .closest("div");

    expect(banner.textContent).not.toContain("7151");
  });

  it("renders an empty value rather than the word undefined", () => {
    const { container } = render(<PrintableForm data={{ fullName: "X" }} />);

    expect(container.textContent).not.toContain("undefined");
  });
});
