import { z } from 'zod';
import { EmploymentStatus, EmploymentType, PayFrequency } from '../models/Employee';

export const createEmployeeSchema = z.object({
  body: z.object({
    personalInfo: z.object({
      firstName: z.string().min(1).max(50),
      lastName: z.string().min(1).max(50),
      middleName: z.string().max(50).optional(),
      email: z.string().email(),
      personalEmail: z.string().email().optional(),
      phone: z.string().max(20),
      alternatePhone: z.string().max(20).optional(),
      dateOfBirth: z.string().datetime(),
      gender: z.enum(['MALE', 'FEMALE', 'OTHER']),
      maritalStatus: z.enum(['SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED']),
      nationality: z.string().max(50).default('Indian'),
      bloodGroup: z.string().optional(),
      religion: z.string().optional(),
      address: z.object({
        line1: z.string().min(1).max(200),
        line2: z.string().max(200).optional(),
        city: z.string().min(1).max(100),
        state: z.string().min(1).max(100),
        country: z.string().max(100).default('India'),
        postalCode: z.string().min(1).max(20),
        isCurrent: z.boolean().default(true),
      }),
      emergencyContact: z.object({
        name: z.string().min(1).max(100),
        relationship: z.string().min(1).max(50),
        phone: z.string().min(1).max(20),
        email: z.string().email().optional(),
        address: z.string().max(200).optional(),
      }),
    }),
    employmentDetails: z.object({
      branchId: z.string().min(1, 'Branch is required'),
      departmentId: z.string().min(1, 'Department is required'),
      designationId: z.string().min(1, 'Designation is required'),
      reportingManagerId: z.string().optional(),
      employmentType: z.nativeEnum(EmploymentType).default(EmploymentType.FULL_TIME),
      employmentStatus: z.nativeEnum(EmploymentStatus).default(EmploymentStatus.PROBATION),
      joiningDate: z.string().datetime(),
      confirmationDate: z.string().datetime().optional(),
      probationEndDate: z.string().datetime().optional(),
      contractEndDate: z.string().datetime().optional(),
      noticePeriodDays: z.number().int().min(0).default(30),
      payFrequency: z.nativeEnum(PayFrequency).default(PayFrequency.MONTHLY),
      workLocation: z.enum(['OFFICE', 'REMOTE', 'HYBRID']).default('OFFICE'),
      shiftId: z.string().optional(),
      employeeGrade: z.string().optional(),
      employeeCategory: z.string().optional(),
    }),
    bankDetails: z.array(z.object({
      accountHolderName: z.string().min(1).max(100),
      accountNumber: z.string().min(1).max(30),
      ifscCode: z.string().min(1).max(15).toUpperCase(),
      bankName: z.string().min(1).max(100),
      branchName: z.string().min(1).max(100),
      accountType: z.enum(['SAVINGS', 'CURRENT']),
      isPrimary: z.boolean().default(true),
      upiId: z.string().optional(),
    })).optional(),
    statutoryDetails: z.object({
      panNumber: z.string().max(10).toUpperCase().optional(),
      aadhaarNumber: z.string().max(12).optional(),
      uanNumber: z.string().max(20).optional(),
      esicNumber: z.string().max(20).optional(),
      pfNumber: z.string().max(20).optional(),
      passportNumber: z.string().max(20).optional(),
      passportExpiry: z.string().datetime().optional(),
      drivingLicenseNumber: z.string().max(20).optional(),
      drivingLicenseExpiry: z.string().datetime().optional(),
      voterId: z.string().max(20).optional(),
    }).optional(),
  }),
});

export const updateEmployeeSchema = z.object({
  body: z.object({
    personalInfo: z.object({
      firstName: z.string().min(1).max(50).optional(),
      lastName: z.string().min(1).max(50).optional(),
      middleName: z.string().max(50).optional(),
      personalEmail: z.string().email().optional(),
      phone: z.string().max(20).optional(),
      alternatePhone: z.string().max(20).optional(),
      bloodGroup: z.string().optional(),
      religion: z.string().optional(),
      address: z.object({
        line1: z.string().max(200).optional(),
        line2: z.string().max(200).optional(),
        city: z.string().max(100).optional(),
        state: z.string().max(100).optional(),
        country: z.string().max(100).optional(),
        postalCode: z.string().max(20).optional(),
        isCurrent: z.boolean().optional(),
      }).optional(),
      emergencyContact: z.object({
        name: z.string().max(100).optional(),
        relationship: z.string().max(50).optional(),
        phone: z.string().max(20).optional(),
        email: z.string().email().optional(),
        address: z.string().max(200).optional(),
      }).optional(),
    }).optional(),
    employmentDetails: z.object({
      branchId: z.string().optional(),
      departmentId: z.string().optional(),
      designationId: z.string().optional(),
      reportingManagerId: z.string().optional(),
      employmentType: z.nativeEnum(EmploymentType).optional(),
      employmentStatus: z.nativeEnum(EmploymentStatus).optional(),
      confirmationDate: z.string().datetime().optional(),
      probationEndDate: z.string().datetime().optional(),
      contractEndDate: z.string().datetime().optional(),
      resignationDate: z.string().datetime().optional(),
      lastWorkingDay: z.string().datetime().optional(),
      terminationDate: z.string().datetime().optional(),
      terminationReason: z.string().max(500).optional(),
      noticePeriodDays: z.number().int().min(0).optional(),
      payFrequency: z.nativeEnum(PayFrequency).optional(),
      currentSalary: z.string().optional(),
      workLocation: z.enum(['OFFICE', 'REMOTE', 'HYBRID']).optional(),
      shiftId: z.string().optional(),
      employeeGrade: z.string().optional(),
      employeeCategory: z.string().optional(),
    }).optional(),
    bankDetails: z.array(z.object({
      accountHolderName: z.string().max(100),
      accountNumber: z.string().max(30),
      ifscCode: z.string().max(15).toUpperCase(),
      bankName: z.string().max(100),
      branchName: z.string().max(100),
      accountType: z.enum(['SAVINGS', 'CURRENT']),
      isPrimary: z.boolean(),
      upiId: z.string().optional(),
    })).optional(),
    statutoryDetails: z.object({
      panNumber: z.string().max(10).toUpperCase().optional(),
      aadhaarNumber: z.string().max(12).optional(),
      uanNumber: z.string().max(20).optional(),
      esicNumber: z.string().max(20).optional(),
      pfNumber: z.string().max(20).optional(),
      passportNumber: z.string().max(20).optional(),
      passportExpiry: z.string().datetime().optional(),
      drivingLicenseNumber: z.string().max(20).optional(),
      drivingLicenseExpiry: z.string().datetime().optional(),
      voterId: z.string().max(20).optional(),
    }).optional(),
    tags: z.array(z.string()).optional(),
    notes: z.string().max(2000).optional(),
  }),
});

export const employeeQuerySchema = z.object({
  query: z.object({
    page: z.coerce.number().int().positive().default(1),
    limit: z.coerce.number().int().positive().max(100).default(20),
    search: z.string().optional(),
    sortBy: z.string().optional(),
    sortOrder: z.enum(['asc', 'desc']).optional(),
    branchId: z.string().optional(),
    departmentId: z.string().optional(),
    employmentStatus: z.nativeEnum(EmploymentStatus).optional(),
    employmentType: z.nativeEnum(EmploymentType).optional(),
    startDate: z.string().datetime().optional(),
    endDate: z.string().datetime().optional(),
  }),
});

export const employeeParamsSchema = z.object({
  params: z.object({
    id: z.string().min(1, 'Employee ID is required'),
  }),
});

export const employeeIdSchema = z.object({
  params: z.object({
    employeeId: z.string().min(1, 'Employee ID is required'),
  }),
});