import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import { FileText, CheckCircle, FileSpreadsheet, Loader2, RefreshCw } from "lucide-react";
import { ticketApi } from "../../utils/api";
import { useAuth } from "../../context/AuthContext";
import { saveJsonToXlsx, downloadCsvFile } from "../../utils/excel";

/**
 * Ticket reports.
 *
 * Every report here is generated by /api/tickets/reports from the caller's own
 * visible tickets, and the export writes the rows on screen. The previous
 * version ran a one-second timer and announced "Exported successfully" without
 * fetching or producing anything — the buttons worked, the file never existed.
 */

const REPORTS = [
  { id: "company_wise", label: "Company-wise", desc: "Volume, resolution and overdue counts per company." },
  { id: "branch_wise", label: "Branch-wise", desc: "Ticket load and SLA outcomes per branch/unit." },
  { id: "department_wise", label: "Department-wise", desc: "Ticket load and resolution time per department." },
  { id: "category_wise", label: "Category-wise", desc: "Which categories generate the most work." },
  { id: "employee_wise", label: "Employee-wise", desc: "Tickets raised per employee." },
  { id: "sla", label: "SLA Compliance", desc: "Within-target vs breached, and average response time, by priority." },
  { id: "resolution_time", label: "Resolution Time", desc: "First response and resolution averages by priority." },
  { id: "escalation", label: "Escalation Report", desc: "Every ticket that has been escalated at least once." },
  { id: "high_priority", label: "High & Urgent", desc: "All high and urgent priority tickets." },
  { id: "overdue", label: "Overdue Tickets", desc: "Active tickets past their SLA target." },
];

export default function TicketReportsView() {
  const { user } = useAuth();
  const accessToken = user?.accessToken;
  const tokenType = user?.tokenType;

  const [reportType, setReportType] = useState("department_wise");
  const [from, setFrom] = useState("");
  const [to, setTo] = useState("");
  const [rows, setRows] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generatedAt, setGeneratedAt] = useState(null);

  const requestReport = async () => {
    try {
      const res = await ticketApi.getReports(reportType, { from, to }, accessToken, tokenType);
      if (res?.status) {
        setRows(res.data?.rows ?? []);
        setGeneratedAt(res.data?.generated_at ?? null);
      }
    } finally {
      setLoading(false);
    }
  };

  const load = () =>
    requestReport().catch((err) => toast.error(err.message || "Failed to generate report"));

  // Spinner raised during render so the effect never sets state synchronously.
  const key = `${reportType}|${from}|${to}`;
  const [keySeen, setKeySeen] = useState(key);
  if (keySeen !== key) {
    setKeySeen(key);
    setLoading(true);
  }

  useEffect(() => {
    load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [key]);

  const columns = rows.length > 0 ? Object.keys(rows[0]) : [];
  const activeReport = REPORTS.find((r) => r.id === reportType);

  const stamp = () => new Date().toISOString().slice(0, 10);

  // Awaited: saveJsonToXlsx builds the workbook asynchronously, so announcing
  // success without waiting would claim a download that had not happened — and
  // would swallow the failure if it never did.
  const exportExcel = async () => {
    if (rows.length === 0) {
      toast.error("This report has no rows to export");
      return;
    }
    try {
      await saveJsonToXlsx(
        `ticket_${reportType}_${stamp()}.xlsx`,
        activeReport?.label?.slice(0, 30) || "Report",
        rows,
      );
      toast.success("Report downloaded");
    } catch (err) {
      toast.error(err.message || "Could not build the spreadsheet");
    }
  };

  const exportCsv = () => {
    if (rows.length === 0) {
      toast.error("This report has no rows to export");
      return;
    }
    try {
      // The shared helper already quotes and escapes each cell.
      downloadCsvFile(`ticket_${reportType}_${stamp()}.csv`, rows);
      toast.success("Report downloaded");
    } catch (err) {
      toast.error(err.message || "Could not build the CSV");
    }
  };

  return (
    <div className="space-y-5">
      <header className="flex flex-wrap items-center justify-between gap-4 border-b border-gray-200 pb-4 dark:border-white/10">
        <div>
          <h2 className="text-lg font-bold text-gray-900 dark:text-white">Reports &amp; Analytics</h2>
          <p className="text-xs text-gray-500 dark:text-gray-400">
            Generated from the tickets you have access to.
            {generatedAt && <> Last run {new Date(generatedAt).toLocaleString("en-IN")}.</>}
          </p>
        </div>
        <div className="flex flex-wrap gap-2">
          <input type="date" value={from} onChange={(e) => setFrom(e.target.value)} className={inputCls} title="From date" />
          <input type="date" value={to} onChange={(e) => setTo(e.target.value)} className={inputCls} title="To date" />
          <button onClick={load} className={btnGhost} title="Re-run report">
            <RefreshCw size={14} className={loading ? "animate-spin" : ""} />
          </button>
          <button onClick={exportCsv} disabled={rows.length === 0} className={btnGhost}>
            <FileText size={14} /> CSV
          </button>
          <button
            onClick={exportExcel}
            disabled={rows.length === 0}
            className="inline-flex items-center gap-1.5 rounded-xl bg-emerald-600 px-4 py-2 text-xs font-bold text-white hover:bg-emerald-700 disabled:opacity-40"
          >
            <FileSpreadsheet size={14} /> Export Excel
          </button>
        </div>
      </header>

      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">
        {REPORTS.map((r) => {
          const selected = reportType === r.id;
          return (
            <button
              key={r.id}
              onClick={() => setReportType(r.id)}
              className={`flex flex-col rounded-2xl border p-3 text-left transition ${
                selected
                  ? "border-brand-600 bg-brand-50/60 ring-2 ring-brand-500/20 dark:border-brand-500 dark:bg-brand-950/20"
                  : "border-gray-200 bg-white hover:border-gray-300 dark:border-white/10 dark:bg-[#0b0f1a]"
              }`}
            >
              <div className="flex items-center justify-between gap-2">
                <span className="text-xs font-bold text-gray-900 dark:text-white">{r.label}</span>
                {selected && <CheckCircle size={15} className="shrink-0 text-brand-600 dark:text-brand-400" />}
              </div>
              <p className="mt-1.5 text-[11px] leading-relaxed text-gray-500 dark:text-gray-400">{r.desc}</p>
            </button>
          );
        })}
      </div>

      <div className="overflow-hidden rounded-2xl border border-gray-200 bg-white dark:border-white/10 dark:bg-[#0b0f1a]">
        <div className="flex items-center justify-between border-b border-gray-100 px-4 py-3 dark:border-white/10">
          <h3 className="text-xs font-bold uppercase tracking-wider text-gray-700 dark:text-gray-300">
            {activeReport?.label}
          </h3>
          <span className="text-[11px] text-gray-400">
            {loading ? "Running…" : `${rows.length} row${rows.length === 1 ? "" : "s"}`}
          </span>
        </div>

        {loading ? (
          <div className="flex h-40 items-center justify-center">
            <Loader2 className="animate-spin text-brand-500" size={20} />
          </div>
        ) : rows.length === 0 ? (
          <p className="px-4 py-12 text-center text-xs text-gray-400">
            No data for this report in the selected period.
          </p>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead className="bg-gray-50 uppercase tracking-wider text-gray-500 dark:bg-slate-900">
                <tr>
                  {columns.map((col) => (
                    <th key={col} className="whitespace-nowrap p-3 font-bold">{col}</th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100 dark:divide-white/10">
                {rows.map((row, idx) => (
                  <tr key={idx} className="hover:bg-gray-50/60 dark:hover:bg-white/[0.02]">
                    {columns.map((col) => (
                      <td key={col} className="whitespace-nowrap p-3 text-gray-700 dark:text-gray-300">
                        {row[col] === null || row[col] === "" ? "—" : String(row[col])}
                      </td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}

const inputCls =
  "rounded-xl border border-gray-200 bg-white px-2.5 py-2 text-xs text-gray-700 outline-none dark:border-white/10 dark:bg-slate-900 dark:text-gray-200";

const btnGhost =
  "inline-flex items-center gap-1.5 rounded-xl border border-gray-200 bg-white px-3.5 py-2 text-xs font-bold text-gray-700 hover:bg-gray-50 disabled:opacity-40 dark:border-white/10 dark:bg-slate-900 dark:text-gray-200";
