import { Request, Response } from 'express';

const ok = (res: Response, message: string) => res.json({ success: true, message, data: [] });

export const getCandidates = (req: Request, res: Response) => ok(res, 'Candidates');
export const createCandidate = (req: Request, res: Response) => ok(res, 'Created Candidate');
export const getCandidateById = (req: Request, res: Response) => ok(res, 'Candidate Detail');
export const updateCandidate = (req: Request, res: Response) => ok(res, 'Updated Candidate');
export const deleteCandidate = (req: Request, res: Response) => ok(res, 'Deleted Candidate');
export const getCandidateTimeline = (req: Request, res: Response) => ok(res, 'Candidate Timeline');
export const addCandidateNote = (req: Request, res: Response) => ok(res, 'Added Note');
export const addCandidateTags = (req: Request, res: Response) => ok(res, 'Added Tags');
export const removeCandidateTag = (req: Request, res: Response) => ok(res, 'Removed Tag');
export const addCommunication = (req: Request, res: Response) => ok(res, 'Added Communication');
export const getCommunications = (req: Request, res: Response) => ok(res, 'Communications');
export const uploadDocument = (req: Request, res: Response) => ok(res, 'Uploaded Document');
export const getDocuments = (req: Request, res: Response) => ok(res, 'Documents');
export const deleteDocument = (req: Request, res: Response) => ok(res, 'Deleted Document');
export const moveCandidateStage = (req: Request, res: Response) => ok(res, 'Moved Stage');
export const scheduleInterview = (req: Request, res: Response) => ok(res, 'Scheduled Interview');
export const submitInterviewFeedback = (req: Request, res: Response) => ok(res, 'Submitted Feedback');
export const getInterviews = (req: Request, res: Response) => ok(res, 'Interviews');
export const extendOffer = (req: Request, res: Response) => ok(res, 'Extended Offer');
export const updateOffer = (req: Request, res: Response) => ok(res, 'Updated Offer');
export const acceptOffer = (req: Request, res: Response) => ok(res, 'Accepted Offer');
export const declineOffer = (req: Request, res: Response) => ok(res, 'Declined Offer');
export const getOffers = (req: Request, res: Response) => ok(res, 'Offers');
export const convertToEmployee = (req: Request, res: Response) => ok(res, 'Converted to Employee');
export const getPipelineStats = (req: Request, res: Response) => ok(res, 'Pipeline Stats');
export const getSourceStats = (req: Request, res: Response) => ok(res, 'Source Stats');
export const getTimeToHireStats = (req: Request, res: Response) => ok(res, 'Time to Hire Stats');
export const getConversionStats = (req: Request, res: Response) => ok(res, 'Conversion Stats');
export const getJobPostings = (req: Request, res: Response) => ok(res, 'Job Postings');
export const createJobPosting = (req: Request, res: Response) => ok(res, 'Created Job Posting');
export const getJobPostingById = (req: Request, res: Response) => ok(res, 'Job Posting Detail');
export const updateJobPosting = (req: Request, res: Response) => ok(res, 'Updated Job Posting');
export const deleteJobPosting = (req: Request, res: Response) => ok(res, 'Deleted Job Posting');
export const publishJobPosting = (req: Request, res: Response) => ok(res, 'Published Job Posting');
export const unpublishJobPosting = (req: Request, res: Response) => ok(res, 'Unpublished Job Posting');
export const closeJobPosting = (req: Request, res: Response) => ok(res, 'Closed Job Posting');
export const getJobPostingApplications = (req: Request, res: Response) => ok(res, 'Job Applications');
export const getJobPostingStats = (req: Request, res: Response) => ok(res, 'Job Stats');
export const duplicateJobPosting = (req: Request, res: Response) => ok(res, 'Duplicated Job Posting');
export const getApplications = (req: Request, res: Response) => ok(res, 'Applications');
export const createApplication = (req: Request, res: Response) => ok(res, 'Created Application');
export const getApplicationById = (req: Request, res: Response) => ok(res, 'Application Detail');
export const updateApplication = (req: Request, res: Response) => ok(res, 'Updated Application');
export const deleteApplication = (req: Request, res: Response) => ok(res, 'Deleted Application');
export const withdrawApplication = (req: Request, res: Response) => ok(res, 'Withdrawn Application');
export const screenApplication = (req: Request, res: Response) => ok(res, 'Screened Application');
export const shortlistApplication = (req: Request, res: Response) => ok(res, 'Shortlisted Application');
export const rejectApplication = (req: Request, res: Response) => ok(res, 'Rejected Application');
export const getUpcomingInterviews = (req: Request, res: Response) => ok(res, 'Upcoming Interviews');
export const getInterviewById = (req: Request, res: Response) => ok(res, 'Interview Detail');
export const updateInterview = (req: Request, res: Response) => ok(res, 'Updated Interview');
export const rescheduleInterview = (req: Request, res: Response) => ok(res, 'Rescheduled Interview');
export const cancelInterview = (req: Request, res: Response) => ok(res, 'Cancelled Interview');
export const getInterviewFeedback = (req: Request, res: Response) => ok(res, 'Interview Feedback');
export const consolidateFeedback = (req: Request, res: Response) => ok(res, 'Consolidated Feedback');
export const getOfferById = (req: Request, res: Response) => ok(res, 'Offer Detail');
export const sendOffer = (req: Request, res: Response) => ok(res, 'Sent Offer');
export const withdrawOffer = (req: Request, res: Response) => ok(res, 'Withdrawn Offer');
export const getPipelineReport = (req: Request, res: Response) => ok(res, 'Pipeline Report');
export const getSourceEffectivenessReport = (req: Request, res: Response) => ok(res, 'Source Effectiveness Report');
export const getTimeToFillReport = (req: Request, res: Response) => ok(res, 'Time to Fill Report');
export const getCostPerHireReport = (req: Request, res: Response) => ok(res, 'Cost per Hire Report');
export const getOfferAcceptanceReport = (req: Request, res: Response) => ok(res, 'Offer Acceptance Report');
export const getInterviewLoadReport = (req: Request, res: Response) => ok(res, 'Interview Load Report');
export const getDiversityReport = (req: Request, res: Response) => ok(res, 'Diversity Report');
export const bulkImportCandidates = (req: Request, res: Response) => ok(res, 'Bulk Import Candidates');
export const bulkUpdateCandidateStatus = (req: Request, res: Response) => ok(res, 'Bulk Update Candidates');
export const bulkImportApplications = (req: Request, res: Response) => ok(res, 'Bulk Import Applications');
export const bulkScheduleInterviews = (req: Request, res: Response) => ok(res, 'Bulk Schedule Interviews');
