<?php

namespace App\Services\Mediclaim\Support;

use App\Models\DocumentVersion;
use App\Models\User;
use App\Services\Documents\DocumentService;
use Illuminate\Http\UploadedFile;
use RuntimeException;

/**
 * Shared glue between dompdf's raw PDF bytes (`Pdf::loadView(...)->output()`
 * returns a plain string) and the existing DocumentService upload pipeline,
 * which is built around a real `Illuminate\Http\UploadedFile` that arrived
 * over HTTP. Both `MediclaimCardService` (card PDFs) and
 * `MediclaimClaimFormPdfService` (final claim-form PDFs) go through here so
 * there is exactly one place that:
 *
 *   1. spools the generated bytes to a real temp file — `UploadedFile` and
 *      `FileValidator`'s content-sniffing (magic-byte check, mime detection)
 *      both need an actual file on disk, not an in-memory string;
 *   2. wraps it as an `UploadedFile` in "test" mode (`$test = true` is the
 *      documented Symfony/Laravel way to hand the upload pipeline a
 *      server-generated file rather than one that came from a real HTTP
 *      multipart request — it bypasses the `is_uploaded_file()` check that
 *      would otherwise make `UploadedFile::isValid()` fail for every
 *      server-side file);
 *   3. guarantees the temp file is removed afterwards regardless of outcome.
 *      `DocumentService`'s `LocalStorageProvider::put()` renames (moves) the
 *      source file, which incidentally cleans it up, but
 *      `S3StorageProvider::put()` only reads it — relying on the storage
 *      layer to clean up would silently leak temp files whenever S3 storage
 *      is configured, so the cleanup here does not assume either behaviour.
 *
 * FIXED (previously flagged here — see the B6 handoff notes): by default
 * `DocumentService::reserveVersion()` deduplicates `Document` rows by
 * `(document_type, owner->id)` alone, then appends a new *version* under
 * whichever `Document` row already exists for that pair. That is correct for
 * "one current document per person" types (PAN card, Aadhaar card, ...), but
 * INSURANCE_CARD and MEDICLAIM_CLAIM_FORM are "many independent documents per
 * person" types — one card per covered member, one final-form PDF per claim.
 * Since `MediclaimDocumentLink` only stores `document_id` (not a specific
 * version), every card/claim-form PDF generated for the SAME employee used to
 * collapse into new versions of ONE shared `Document` row, and every existing
 * link to that row would then resolve to whichever version was uploaded most
 * recently. `DocumentService::upload()`/`reserveVersion()` now accept an
 * optional trailing `$scopeKey` (null by default, so every other caller in
 * the app is unaffected) which, when passed, becomes part of the Document's
 * identity — see reserveVersion()'s docblock. `MediclaimCardService` and
 * `MediclaimClaimFormPdfService` both now pass a distinguishing scope key
 * through this method's own `$scopeKey` parameter, and `ClaimDocumentController`
 * (B4's per-claim upload endpoint) does the same directly against
 * `DocumentService::upload()`.
 */
class GeneratedPdfUploader
{
    public static function upload(
        string $pdfBytes,
        string $downloadFileName,
        User $owner,
        string $documentType,
        int $actorId,
        ?string $scopeKey = null
    ): DocumentVersion {
        $tempPath = tempnam(sys_get_temp_dir(), 'mc_pdf_');

        if ($tempPath === false) {
            throw new RuntimeException('Could not allocate a temporary file for PDF generation.');
        }

        try {
            file_put_contents($tempPath, $pdfBytes);

            // $test = true: see class docblock point 2.
            $uploadedFile = new UploadedFile($tempPath, $downloadFileName, 'application/pdf', null, true);

            return DocumentService::make()->upload($uploadedFile, $owner, $documentType, $actorId, scopeKey: $scopeKey);
        } finally {
            if (is_file($tempPath)) {
                @unlink($tempPath);
            }
        }
    }
}
