export const MOCK_USER_EMPLOYEE = {
  id: 1042,
  empCode: 'EMP-1042',
  name: 'Alex Mercer',
  email: 'alex.mercer@enterprise-hrms.com',
  phone: '+1 (555) 234-5678',
  designation: 'Senior Product Engineer',
  department: 'Engineering & Innovation',
  unit: 'HQ - Building Alpha',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
  joiningDate: '15 Jan 2022',
  manager: 'Sarah Jenkins',
  role: 'employee', // 'employee' or 'agent'
  company: 'NISS Enterprise Solutions',
  digitalIdQr: 'NISS-EMP-1042-VERIFIED',
};

export const MOCK_USER_AGENT = {
  ...MOCK_USER_EMPLOYEE,
  name: 'Alex Mercer (Agent Desk)',
  designation: 'Senior Operations Agent & Support Lead',
  department: 'IT & Facilities Support',
  role: 'agent',
};

export const MOCK_ATTENDANCE = {
  isPunchedIn: true,
  punchInTime: '09:05 AM',
  punchOutTime: null,
  totalHoursToday: '07h 45m',
  shiftName: 'Standard Day Shift',
  shiftTiming: '09:00 AM - 06:00 PM',
  location: 'HQ Alpha - Floor 4 (Verified GPS)',
  monthlySummary: {
    present: 22,
    absent: 1,
    leaves: 2,
    lateCount: 1,
    punctualityRate: '95.6%',
    overtimeHours: '14.5 hrs',
  },
  recentLogs: [
    { date: 'Today, Aug 07', punchIn: '09:05 AM', punchOut: '--:--', hours: '7h 45m', status: 'On Duty' },
    { date: 'Thu, Aug 06', punchIn: '08:58 AM', punchOut: '06:12 PM', hours: '9h 14m', status: 'Present' },
    { date: 'Wed, Aug 05', punchIn: '09:12 AM', punchOut: '06:05 PM', hours: '8h 53m', status: 'Late Check-in' },
    { date: 'Tue, Aug 04', punchIn: '08:55 AM', punchOut: '06:30 PM', hours: '9h 35m', status: 'Present' },
    { date: 'Mon, Aug 03', punchIn: '09:00 AM', punchOut: '06:00 PM', hours: '9h 00m', status: 'Present' },
  ],
};

export const MOCK_LEAVES = {
  quotas: [
    { type: 'Casual Leave', code: 'CL', remaining: 6, total: 12, color: '#6366F1', bg: 'rgba(99, 102, 241, 0.15)' },
    { type: 'Earned Leave', code: 'EL', remaining: 14, total: 18, color: '#10B981', bg: 'rgba(16, 185, 129, 0.15)' },
    { type: 'Sick Leave', code: 'SL', remaining: 7, total: 10, color: '#F59E0B', bg: 'rgba(245, 158, 11, 0.15)' },
  ],
  applications: [
    { id: 'LV-902', type: 'Casual Leave', dates: '14 Aug - 15 Aug (2 Days)', reason: 'Personal family occasion', status: 'Approved', approvedBy: 'Sarah Jenkins', appliedOn: '04 Aug 2026' },
    { id: 'LV-884', type: 'Sick Leave', dates: '22 Jul (1 Day)', reason: 'Dental appointment & recovery', status: 'Approved', approvedBy: 'Sarah Jenkins', appliedOn: '21 Jul 2026' },
    { id: 'LV-760', type: 'Earned Leave', dates: '10 Sep - 18 Sep (7 Days)', reason: 'Annual vacation trip', status: 'Pending Approval', approvedBy: 'HR Desk', appliedOn: '06 Aug 2026' },
  ],
};

export const MOCK_TICKETS = [
  {
    id: 'TK-4029',
    category: 'IT Support',
    subject: 'MacBook Pro M3 External Display Flicker',
    description: 'The USB-C display port intermittently disconnects when using dual monitors at Workstation 4B.',
    department: 'IT Infrastructure',
    priority: 'High',
    status: 'In Progress',
    assignedTo: 'Marcus Vance (Senior IT Tech)',
    createdDate: 'Today, 10:30 AM',
    slaTimeRemaining: '3h 15m remaining',
    commentsCount: 3,
    lastUpdate: 'Agent added internal diagnostic note',
  },
  {
    id: 'TK-3982',
    category: 'Payroll & Compensation',
    subject: 'Tax Deduction Clarification for July Slip',
    description: 'Need breakdown of Section 80C investment deduction applied on July 2026 payslip.',
    department: 'Payroll & Accounts',
    priority: 'Medium',
    status: 'Pending',
    assignedTo: 'Unassigned (Payroll Queue)',
    createdDate: 'Yesterday, 04:15 PM',
    slaTimeRemaining: '18h remaining',
    commentsCount: 1,
    lastUpdate: 'Ticket raised by employee',
  },
  {
    id: 'TK-3850',
    category: 'Facilities & Asset',
    subject: 'Ergonomic Chair Adjustment Request',
    description: 'Lumbar support handle broken on chair #FAC-9912.',
    department: 'Facilities Management',
    priority: 'Low',
    status: 'Resolved',
    assignedTo: 'David Miller (Facilities)',
    createdDate: '01 Aug 2026',
    slaTimeRemaining: 'SLA Met',
    commentsCount: 4,
    lastUpdate: 'Replacement chair issued',
  },
];

export const MOCK_AGENT_TICKETS = [
  {
    id: 'TK-4102',
    category: 'IT Hardware',
    subject: 'VPN Connection Drop for Remote Agent Team',
    employeeName: 'Rohan Sharma (Emp #1092)',
    employeeDept: 'Field Sales',
    priority: 'High',
    status: 'In Progress',
    slaTimeRemaining: '1h 45m (URGENT)',
    createdDate: '11:15 AM',
    description: 'Agent unable to sync field reports due to gateway timeout on SSL VPN.',
  },
  {
    id: 'TK-4088',
    category: 'Asset Allocation',
    subject: 'New Joining Laptop Setup for Design Unit',
    employeeName: 'Maya Lin (Emp #1105)',
    employeeDept: 'UX & Design',
    priority: 'Medium',
    status: 'Open',
    slaTimeRemaining: '8h 30m',
    createdDate: '09:40 AM',
    description: 'Pre-configure Adobe Creative Cloud and Figma enterprise license.',
  },
  {
    id: 'TK-3990',
    category: 'Access & Security',
    subject: 'Server Room Floor 3 Access Card Revocation',
    employeeName: 'Security Ops',
    employeeDept: 'Administration',
    priority: 'Urgent',
    status: 'Escalated',
    slaTimeRemaining: 'SLA Breached (Action Required)',
    createdDate: 'Yesterday',
    description: 'Deactivate badge #SEC-881 immediately following role transfer.',
  },
];

export const MOCK_FIELD_TASKS = [
  {
    id: 'FTS-904',
    title: 'North Hub Infrastructure Inspection',
    client: 'NISS Logistics Center',
    address: 'Plot 44, Tech Corridor, Zone 2',
    scheduledTime: 'Today, 02:30 PM',
    priority: 'High',
    status: 'Assigned',
    gpsTarget: '28.6139° N, 77.2090° E',
    instructions: 'Verify biometric reader installation and test offline power backup unit.',
  },
  {
    id: 'FTS-892',
    title: 'Onsite Asset Audit - West Wing',
    client: 'Enterprise Branch #04',
    address: 'Building B, Finance Park',
    scheduledTime: 'Tomorrow, 10:00 AM',
    priority: 'Medium',
    status: 'Pending',
    gpsTarget: '28.5355° N, 77.3910° E',
    instructions: 'Scan barcoded printers and monitors for quarterly inventory audit.',
  },
];

export const MOCK_PAYSLIPS = [
  {
    id: 'PS-2026-07',
    monthYear: 'July 2026',
    payPeriod: '01 Jul 2026 - 31 Jul 2026',
    grossPay: '$8,450.00',
    totalDeductions: '$1,220.00',
    netPay: '$7,230.00',
    paymentStatus: 'Paid (Direct Deposit)',
    paymentDate: '31 Jul 2026',
    bankName: 'Chase Commercial Bank',
    accountEnding: '•••• 8821',
    earnings: [
      { name: 'Basic Salary', amount: '$4,500.00' },
      { name: 'House Rent Allowance (HRA)', amount: '$1,800.00' },
      { name: 'Special Performance Allowance', amount: '$1,500.00' },
      { name: 'Conveyance Allowance', amount: '$650.00' },
    ],
    deductions: [
      { name: 'Provident Fund (PF)', amount: '$540.00' },
      { name: 'Income Tax (TDS)', amount: '$580.00' },
      { name: 'Health & Medical Insurance', amount: '$100.00' },
    ],
  },
  {
    id: 'PS-2026-06',
    monthYear: 'June 2026',
    payPeriod: '01 Jun 2026 - 30 Jun 2026',
    grossPay: '$8,450.00',
    totalDeductions: '$1,220.00',
    netPay: '$7,230.00',
    paymentStatus: 'Paid',
    paymentDate: '30 Jun 2026',
    bankName: 'Chase Commercial Bank',
    accountEnding: '•••• 8821',
    earnings: [
      { name: 'Basic Salary', amount: '$4,500.00' },
      { name: 'House Rent Allowance (HRA)', amount: '$1,800.00' },
      { name: 'Special Allowance', amount: '$1,500.00' },
      { name: 'Conveyance Allowance', amount: '$650.00' },
    ],
    deductions: [
      { name: 'Provident Fund (PF)', amount: '$540.00' },
      { name: 'Income Tax (TDS)', amount: '$580.00' },
      { name: 'Health Insurance', amount: '$100.00' },
    ],
  },
];

export const MOCK_NOTIFICATIONS = [
  {
    id: 'NT-101',
    title: 'Leave Approved',
    message: 'Your Casual Leave application for Aug 14 - Aug 15 has been approved by Sarah Jenkins.',
    time: '10 mins ago',
    type: 'leave',
    read: false,
  },
  {
    id: 'NT-102',
    title: 'Ticket Status Updated',
    message: 'Ticket #TK-4029 has been updated to "In Progress" by IT Support.',
    time: '1 hour ago',
    type: 'ticket',
    read: false,
  },
  {
    id: 'NT-103',
    title: 'July Salary Slip Available',
    message: 'Your salary slip for July 2026 is ready for download and view in the Payslip tab.',
    time: '1 day ago',
    type: 'payroll',
    read: true,
  },
  {
    id: 'NT-104',
    title: 'Company Townhall Announcement',
    message: 'Q3 Enterprise All-Hands is scheduled for Thursday, Aug 20 at 04:00 PM EST.',
    time: '2 days ago',
    type: 'announcement',
    read: true,
  },
];
